services:
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo_db
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DATABASE_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DATABASE_PASSWORD
    ports:
      - "$MONGO_DATABASE_PORT:27017"